[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-clans-api"
version = "0.1.0"
description = ""
authors = [
    { name = "niko-at-chalupa"},
]
dependencies = [
    "endstone",
    "sqlite3",
]

[project.entry-points."endstone"]
breeze = "endstone_clans_api:ClansApiPlugin"

[tool.hatch.build.targets.wheel]
packages = ["src/endstone_clans_api"]