[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-clans-api"
version = "1.0.1"
description = ""
authors = [
    { name = "niko-at-chalupa"},
]
dependencies = [
    "endstone",
    "pydantic",
    "ruamel.yaml",
    "xxhash",
]

[project.entry-points."endstone"]
clans-api = "endstone_clans_api:ClansApiPlugin"

[tool.hatch.build.targets.wheel]
packages = ["src/endstone_clans_api"]