[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-clans-test"
version = "0.1.0"
description = "Testing plugin for endstone-clans-api"
dependencies = [
    "endstone",
#    "endstone-clans-api @ git+https://github.com/niko-at-chalupa/endstone-clans-api.git"
# Normally you'd do this to list it as a dependancy.
]

[project.entry-points."endstone.plugins"]
endstone_clans_test = "endstone_clans_test:TestPlugin"

[tool.hatch.build.targets.wheel]
packages = ["src/endstone_clans_test"]

[tool.hatch.metadata]
allow-direct-references = true
