from .api import ClansApi as ClansApi
from .database import Database as Database
from .events import ClanCreateEvent as ClanCreateEvent, ClanDeleteEvent as ClanDeleteEvent, ClanInviteEvent as ClanInviteEvent, ClanJoinEvent as ClanJoinEvent, ClanKickEvent as ClanKickEvent, ClanLeaveEvent as ClanLeaveEvent, ClanRenameEvent as ClanRenameEvent
from .main import ClansApiPlugin as ClansApiPlugin, ClansConfig as ClansConfig
from _typeshed import Incomplete
from abc import ABC
from endstone import Logger
from endstone.command import Command, CommandSender
from endstone.scheduler import Scheduler
from typing import Callable

class Subcommands(ABC):
    subcommand_map: dict[str, Callable[[CommandSender, Command, list[str]], bool]]
    plugin: ClansApiPlugin
    @property
    def config(self) -> ClansConfig: ...
    @property
    def messages(self) -> dict[str, str]: ...
    @property
    def db(self) -> Database: ...
    @property
    def scheduler(self) -> Scheduler: ...
    @property
    def logger(self) -> Logger: ...

class ClansCommands(Subcommands):
    def help(self, sender: CommandSender, command: Command, args: list[str]): ...
    def create(self, sender: CommandSender, command: Command, args: list[str]): ...
    def rename(self, sender: CommandSender, command: Command, args: list[str]): ...
    def config_command(self, sender: CommandSender, command: Command, args: list[str]): ...
    def invite(self, sender: CommandSender, command: Command, args: list[str]): ...
    def kick(self, sender: CommandSender, command: Command, args: list[str]): ...
    def leave(self, sender: CommandSender, command: Command, args: list[str]): ...
    plugin: Incomplete
    subcommand_map: Incomplete
    def __init__(self, plugin: ClansApiPlugin) -> None: ...
    @property
    def api(self) -> ClansApi: ...
