import abc
from .etc import remove_minecraft_formatting as remove_minecraft_formatting
from .main import ClansApiPlugin as ClansApiPlugin
from .types import Clan as Clan
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from pathlib import Path

class Database(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def close(self) -> None: ...
    @abstractmethod
    def create_clan(self, name: str, owner_xuid: int) -> None: ...
    @abstractmethod
    def get_clan(self, name: str) -> Clan | None: ...
    @abstractmethod
    def get_clan_by_xuid(self, xuid: int) -> Clan | None: ...
    @abstractmethod
    def get_members_xuids(self, owner_xuid: int) -> set[int]: ...
    @abstractmethod
    def get_member_clan(self, member_xuid: int) -> Clan | None: ...
    @abstractmethod
    def delete_clan(self, owner_xuid: int) -> None: ...
    @abstractmethod
    def rename_clan(self, owner_xuid: int, new_name: str) -> None: ...
    @abstractmethod
    def add_member(self, owner_xuid: int, member_xuid: int) -> None: ...
    @abstractmethod
    def remove_member(self, owner_xuid: int, member_xuid: int) -> None: ...
    @abstractmethod
    def set_player_preference(self, xuid: int, key: str, value: str) -> None: ...
    @abstractmethod
    def get_player_preference(self, xuid: int, key: str) -> str | None: ...

class _Database(Database):
    plugin: Incomplete
    db_path: Incomplete
    def __init__(self, plugin: ClansApiPlugin, db_path: Path) -> None: ...
    def close(self) -> None: ...
    def create_clan(self, name: str, owner_xuid: int) -> None: ...
    def get_clan(self, name: str) -> Clan | None: ...
    def get_clan_by_xuid(self, xuid: int) -> Clan | None: ...
    def get_members_xuids(self, owner_xuid: int) -> set[int]: ...
    def get_member_clan(self, member_xuid: int) -> Clan | None: ...
    def delete_clan(self, owner_xuid: int) -> None: ...
    def rename_clan(self, owner_xuid: int, new_name: str) -> None: ...
    def add_member(self, owner_xuid: int, member_xuid: int) -> None: ...
    def remove_member(self, owner_xuid: int, member_xuid: int) -> None: ...
    def set_player_preference(self, xuid: int, key: str, value: str) -> None: ...
    def get_player_preference(self, xuid: int, key: str) -> str | None: ...
